application.name=MedAn247-NewsFetcher
application.port=8166

datasource.driver-class-name=com.mysql.cj.jdbc.Driver
datasource.url=jdbc:mysql://172.20.4.11:3306/medanbaru
datasource.username=web_app
datasource.password=medanw34pp5

kafka.bootstrap.servers=medan302.solusi247.com:9093
kafka.consumer.group-id=test

solr.is-secure=false
solr.is-cluster=false
solr.host=http://172.20.4.13:8993/solr/mediaonline_staging

api.url-checker=http://172.20.4.11:36868/endpoint/url/urlHandler

# kafka.bootstrap.servers=brj2prdsmlwrk1dbs.solusi247.com:6667,brj2prdsmlwrk2dbs.solusi247.com:6667,brj2prdsmlwrk3dbs.solusi247.com:6667
# kafka.consumer.group-id=medan

# solr.is-secure=true
# solr.is-cluster=true
# solr.zk-host=brj2prdsmlwrk1dbs.solusi247.com:2181
# solr.collection=staging_news